### ISSUE TITLE
NexT主题中如何使用MiniValine

### ISSUE THREAD

**Issue by cmwode** [MiniValine/MiniValine#112]
在使用hexo-next-minivaline时遇到错误
```
$ hexo s
INFO  Start processing
FATAL Something's wrong. Maybe you can find the solution here: https://hexo.io/docs/troubleshooting.html
TypeError: Cannot read property 'enable' of undefined
    at E:\Hexo\node_modules\hexo-next-minivaline\index.js:11:26
    at Filter.execSync (E:\Hexo\node_modules\hexo\lib\extend\filter.js:76:30)
    at Hexo.execFilterSync (E:\Hexo\node_modules\hexo\lib\hexo\index.js:470:31)
    at module.exports (E:\Hexo\themes\next\scripts\events\lib\injects.js:58:8)
    at Hexo.<anonymous> (E:\Hexo\themes\next\scripts\events\index.js:9:27)
    at Hexo.emit (events.js:333:22)
    at Hexo._generate (E:\Hexo\node_modules\hexo\lib\hexo\index.js:437:10)
    at E:\Hexo\node_modules\hexo\lib\hexo\index.js:336:19
    at tryCatcher (E:\Hexo\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (E:\Hexo\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (E:\Hexo\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (E:\Hexo\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (E:\Hexo\node_modules\bluebird\js\release\promise.js:729:18)
    at Promise._fulfill (E:\Hexo\node_modules\bluebird\js\release\promise.js:673:18)
    at PromiseArray._resolve (E:\Hexo\node_modules\bluebird\js\release\promise_array.js:127:19)
    at PromiseArray._promiseFulfilled (E:\Hexo\node_modules\bluebird\js\release\promise_array.js:145:14)
    at Promise._settlePromise (E:\Hexo\node_modules\bluebird\js\release\promise.js:609:26)
    at Promise._settlePromise0 (E:\Hexo\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (E:\Hexo\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (E:\Hexo\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (E:\Hexo\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (E:\Hexo\node_modules\bluebird\js\release\async.js:102:5)
```
您是否不再维护该项目(hexo-next-minivaline)？

在next主题中如何使用minivaline？

**Comment by MHuiG** [comment]
@cmwode: hello! :wave:

This issue is being automatically closed because it does not follow the issue template.

**Comment by MHuiG** [comment]
# 在next主题中如何使用MiniValine？


第一步:
进入Hexo项目文件夹下，安装hexo-next-minivaline
```
npm install hexo-next-minivaline --save
```
![image](https://user-images.githubusercontent.com/38281581/83225677-e23b2900-a1b2-11ea-89ec-551a439a871a.png)

第二步：
修改blog/_config.yml文件（注意：这里是Hexo项目文件夹,NexT主题配置文件不需要任何改动）
![image](https://user-images.githubusercontent.com/38281581/83225863-46f68380-a1b3-11ea-8e8a-654e4a6f72c4.png)
添加配置：
```
minivaline:
  enable: true
  appid: # Your leancloud application appid
  appkey:  # Your leancloud application appkey
  placeholder: Write a Comment O(∩_∩)O~~ # Comment box placeholder
  maxNest: 3 # Nest size
  pageSize: 6 # Pagination size
  adminEmailMd5: # The MD5 of Admin Email to show Admin Flag.
  math: true # Support MathJax.
  md: true # Support Markdown.
  # MiniValine's display language depends on user's browser or system environment
  # If you want everyone visiting your site to see a uniform language, you can set a force language value
  # Available values: en  | zh-CN | (and many more)
  # More i18n info: https://github.com/MiniValine/minivaline-i18n
  language:
  lazyload: false
  cdn: # https://unpkg.com/minivaline/dist/MiniValine.min.js
```
![image](https://user-images.githubusercontent.com/38281581/83226075-b79da000-a1b3-11ea-9053-727d55f14ee4.png)

第三步：
执行hexo s
![image](https://user-images.githubusercontent.com/38281581/83226222-0d724800-a1b4-11ea-8538-6f6615273ec0.png)
