### ISSUE TITLE
Artitalk与MiniValine不兼容

### ISSUE THREAD

**Issue by MCSeekeri** [MiniValine/MiniValine#169]
Please follow this Issue template to provide relevant information, such as source code repositories, blog links, and screenshots, which will help us investigate.
请按照此 Issue 模版提供相关信息，例如源码仓库、博客链接和屏幕截图，这将有助于我们进行调查。

## Issue Checklist 

- [x] I am using [the latest](https://github.com/MiniValine/MiniValine/releases/latest) version of MiniValine.
- [x] I have reviewed the [MiniValine FAQs](https://github.com/MiniValine/MiniValine/blob/master/.github/FAQ.md), which does not help me.
- [x] I have reviewed the latest Roadmap on GitHub and searched for current [issues](https://github.com/MiniValine/MiniValine/issues), which does not help me.

***

我在使用Volantis主题时无法正常使用Artitalk,将评论从MiniValine切换到Valive之后问题解决,推测是MiniValine与Artitalk不兼容。
我确定我在页面中设置了Comments: false
F12报错提示为"storage adapter is not configured"

## Steps to reproduce the behavior 
1. 部署Volantis主题
2. 正常配置Artitalk和MiniValine
3. 访问测试

### MiniValine Configuration

```
minivaline:
    appId: XXXXXXXXXX  #我这里正常配置了,MiniValine和Artitalk并不共享一个App
    appKey: XXXXXXXXXXX
    #js: https://cdn.jsdelivr.net/npm/minivaline@3/dist/MiniValine.min.js
    mode: DesertsP # DesertsP or xCss
    placeholder: 快来评论吧~ # Comment box placeholder
    path: # All pages use the same path (share the same comments data)
    math: false # Support MathJax.
    md: true # Support Markdown.
    enableQQ: true # Enable QQ avatar API.
    NoRecordIP: false # Do not record commenter IP.
    closeFlag: false
    closeUA: false
    region: true
    visitor: true # Article reading statistics.
    maxNest: 6 # Sub-comment maximum nesting depth.
    pageSize: 6 # Pagination size.
    barrager: 0
    role: admin
    #cloudflag: false
    adminEmailMd5: 2fe1b9f7d79c288f4d7b8bc15b0227a4 # The MD5 of Admin Email to show Admin Flag.[ Just Only DesertsP Style mode]
    # tagMeta: # The String Array of Words to show Flag.[ Just Only xCss Style mode]
    #   - 管理员
    #   - 小伙伴
    #   - 访客
    # master: # The MD5 String Array of master Email to show master Flag.[ Just Only xCss Style mode]
    #   - 2fe1b9f7d79c288f4d7b8bc15b0227a4
    # friends: # The MD5 String Array of friends Email to show friends Flag. [ Just Only xCss Style mode]
    #   - xxxxx
    #   - xxxxx
    #   - xxxxx
    #   - xxxxx
```

## Other Information 
初次报错时浏览器为Chromium内核Edge,之后在多台不同环境设备上测试过,依然报错。
