### ISSUE TITLE
在Next8.0版本中无效

### ISSUE THREAD

**Issue by suyin-long** [MiniValine/MiniValine#179]
Please follow this Issue template to provide relevant information, such as source code repositories, blog links, and screenshots, which will help us investigate.
请按照此 Issue 模版提供相关信息，例如源码仓库、博客链接和屏幕截图，这将有助于我们进行调查。

## Issue Checklist 

- [ x ] I am using [the latest](https://github.com/MiniValine/MiniValine/releases/latest) version of MiniValine.
- [ x ] I have reviewed the [MiniValine FAQs](https://github.com/MiniValine/MiniValine/blob/master/.github/FAQ.md), which does not help me.
- [ x ] I have reviewed the latest Roadmap on GitHub and searched for current [issues](https://github.com/MiniValine/MiniValine/issues), which does not help me.

***

## Expected behavior 
在next8.0版本中生效

## Actual behavior 

在next8.0版本中无效

- Links to demo site with this issue: N/A
- Links to repository or source code of the blog: N/A

## Steps to reproduce the behavior 
1. 使用`npm install hexo-theme-next`安装[Next 8.0](https://github.com/next-theme/hexo-theme-next)主题
2. 安装[Hexo Next MiniValine 2.0](https://github.com/MiniValine/hexo-next-minivaline)版本
3. 配置Hexo Next MiniValine 2.0
4. 测试效果

### Node.js and NPM Information

```
v12.18.3
6.14.6
```

### Package dependencies Information

```
hexo-site@0.0.0 E:\Hexo
+-- hexo@5.1.1
+-- hexo-enhancer@1.0.7
+-- hexo-filter-emoji@2.2.1
+-- hexo-generator-archive@1.0.0
+-- hexo-generator-category@1.0.0
+-- hexo-generator-feed@3.0.0
+-- hexo-generator-index@2.0.0
+-- hexo-generator-searchdb@1.3.2
+-- hexo-generator-tag@1.0.0
+-- hexo-helper-live2d@3.1.1
+-- hexo-next-fireworks@1.0.1 (github:next-theme/hexo-next-fireworks#dc3c2eb7c1bbcba7321cf373fb6208df3a75f1d2)
+-- hexo-next-minivaline@2.0.0
+-- hexo-renderer-ejs@1.0.0
+-- hexo-renderer-marked@3.2.0
+-- hexo-renderer-stylus@2.0.0
+-- hexo-server@2.0.0
+-- hexo-submit-urls-to-search-engine@2.0.0
+-- hexo-symbols-count-time@0.7.1
+-- hexo-theme-next@8.0.0
`-- live2d-widget-model-hijiki@1.0.5
```

### HTML Configuration

```

```

### MiniValine Configuration

```

```

## Other Information 
以前用`git clone https://github.com/next-theme/hexo-theme-next themes/next`安装的NexT 8.0.0-rc.5 版本可以正常使用，
现在使用`npm install hexo-theme-next`安装[Next 8.0](https://github.com/next-theme/hexo-theme-next)版本不能正常使用，
猜测是因为Next版本的问题或者是安装Next方式的问题。

**Comment by MHuiG** [comment]
```
v12.14.0
6.14.5
```
```
hexo-site@0.0.0 E:\Github\T
+-- hexo@5.0.2
+-- hexo-cli@3.1.0
+-- hexo-generator-archive@1.0.0
+-- hexo-generator-category@1.0.0
+-- hexo-generator-index@1.0.0
+-- hexo-generator-tag@1.0.0
+-- hexo-next-minivaline@2.0.0
+-- hexo-render-pug@2.1.4
+-- hexo-renderer-ejs@1.0.0
+-- hexo-renderer-marked@2.0.0
+-- hexo-renderer-sass@0.4.0
+-- hexo-renderer-stylus@1.1.0
+-- hexo-server@1.0.0
`-- hexo-theme-next@8.0.0

```

```
# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Hexo
subtitle: ''
description: ''
keywords:
author: John Doe
language: en
timezone: ''

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://yoursite.com
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## Use post's date for updated date unless set in front-matter
use_date_for_updated: false

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next
#theme: landscape

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: ''

minivaline:
  enable: true
  appid: LmbPKvC6CBJTmgzDc5juXS2T-MdYXbMMI # Your leancloud application appid
  appkey: BllY8ze5X84ydj5IBrdmnP3q # Your leancloud application appkey
  mode: xCss # DesertsP or xCss
  placeholder: Write a Comment # Comment box placeholder
  math: true # Support MathJax.
  md: true # Support Markdown.
  enableQQ: true # Enable QQ avatar API.
  NoRecordIP: false # Do not record commenter IP.
  visitor: false # Article reading statistics.
  maxNest: 6 # Sub-comment maximum nesting depth.
  pageSize: 6 # Pagination size.
  adminEmailMd5: de8a7aa53d07e6b6bceb45c64027763d # The MD5 of Admin Email to show Admin Flag.[ Just Only DesertsP Style mode]
  tagMeta: # The String Array of Words to show Flag.[ Just Only xCss Style mode]
    - 管理员
    - 小伙伴
    - 访客
  master: # The MD5 String Array of master Email to show master Flag.[ Just Only xCss Style mode]
    - de8a7aa53d07e6b6bceb45c64027763d
  friends: # The MD5 String Array of friends Email to show friends Flag. [ Just Only xCss Style mode]
    - b5bd5d836c7a0091aa8473e79ed4c25e
    - adb7d1cd192658a55c0ad22a3309cecf
    - 3ce1e6c77b4910f1871106cb30dc62b0
    - cfce8dc43725cc14ffcd9fb4892d5bfc
  # MiniValine's display language depends on user's browser or system environment
  # If you want everyone visiting your site to see a uniform language, you can set a force language value
  # Available values: en  | zh-CN | (and many more)
  # More i18n info: https://github.com/MiniValine/minivaline-i18n
  lang:
  # Expression Url.
  # https://github.com/MiniValine/MiniValine/blob/master/.github/FAQ.md#how-to-customize-emoticons
  emoticonUrl:
    - https://cdn.jsdelivr.net/npm/alus@latest
    - https://cdn.jsdelivr.net/gh/MiniValine/qq@latest
    - https://cdn.jsdelivr.net/gh/MiniValine/Bilibilis@latest
    - https://cdn.jsdelivr.net/gh/MiniValine/tieba@latest
    - https://cdn.jsdelivr.net/gh/MiniValine/twemoji@latest
    - https://cdn.jsdelivr.net/gh/MiniValine/weibo@latest
  lazyload: true
  cdn: https://cdn.jsdelivr.net/npm/minivaline@4/dist/MiniValine.min.js
```
![image](https://user-images.githubusercontent.com/38281581/92245880-8beb2e00-eef7-11ea-80f7-64d5d19c8262.png)
