### ISSUE TITLE
使用Waline后端无法加载评论框、无法显示valine历史评论

### ISSUE THREAD

**Issue by lei2rock** [MiniValine/MiniValine#248]
Please follow this Issue template to provide relevant information, such as source code repositories, blog links, and screenshots, which will help us investigate.
请按照此 Issue 模版提供相关信息，例如源码仓库、博客链接和屏幕截图，这将有助于我们进行调查。

## Issue Checklist 

- [x] I am using [the latest](https://github.com/MiniValine/hexo-next-minivaline/releases/latest) version of hexo-next-minivaline.
- [x] I have reviewed the latest Roadmap on GitHub and searched for current [issues](https://github.com/MiniValine/hexo-next-minivaline/issues), which does not help me.

***

## Expected behavior 
使用Waline后端，加载评论框+加载原来Valine产生的评论数据

## Actual behavior 

- Links to demo site with this issue: N/A
- Links to repository or source code of the blog: N/A

按照说明设置好了，其中`mode: xCss`，并添加了 `backend` 和 `serverURLs`，后端工作正常，可以正常获取Valine产生的评论数据。但是：

Safari下：完全无法加载评论框，并控制台提示 
```
Failed to load resource: the server responded with a status of 404 () https://cdn.jsdelivr.net/npm/minivaline@5.0.0-alpha.2/i18n/zh-cn/index.json?v=05784131981201925
```
Edge下：可以加载评论框，但是语言是英文（强制设置中文也不行），同时不能加载原来Valine产生的评论数据，但是可以显示新产生的评论，控制台提示：
<img width="748" alt="image" src="https://user-images.githubusercontent.com/19180725/100519146-0e228000-31d1-11eb-929a-9f2ec248a5d3.png">

## Steps to reproduce the behavior 
1. N/A
2. N/A
3. N/A

## Environment Information

Hexo 5 和 NexT 8 都是最新的

### Node.js and NPM Information

```

```

### Package dependencies Information

```
"hexo": "^5.2.0"
"hexo-next-minivaline": "^5.2.0"
"hexo-theme-next": "^8.0.2"
```

### hexo-next-minivaline Configuration

```

```

**Comment by lei2rock** [comment]
```
minivaline:
  enable: true
  mversion: latest
  mode: xCss # DesertsP or xCss
  placeholder: Write a Comment # Comment box placeholder
  math: true # Support MathJax.
  md: true # Support Markdown.
  maxNest: 6 # Sub-comment maximum nesting depth.
  pageSize: 6 # Pagination size.
  # MiniValine's display language depends on user's browser or system environment
  # If you want everyone visiting your site to see a uniform language, you can set a force language value
  # Available values: en  | zh-CN | (and many more)
  # More i18n info: https://github.com/MiniValine/minivaline-i18n
  lang: zh-CN
  # Expression Url.
  # https://github.com/MiniValine/MiniValine/blob/master/.github/FAQ.md#how-to-customize-emoticons
  emoticonUrl:
    - https://cdn.jsdelivr.net/npm/alus@latest
    - https://cdn.jsdelivr.net/gh/MiniValine/qq@latest
    - https://cdn.jsdelivr.net/gh/MiniValine/Bilibilis@latest
    - https://cdn.jsdelivr.net/gh/MiniValine/tieba@latest
    - https://cdn.jsdelivr.net/gh/MiniValine/twemoji@latest
    - https://cdn.jsdelivr.net/gh/MiniValine/weibo@latest
  lazyload: false
  cdn: https://cdn.jsdelivr.net/npm/minivaline@latest/dist/MiniValine.min.js
  backend: waline
  serverURLs: https://waline.dlzhang.com
```

其他的可以看 https://github.com/lei2rock/blog 源代码都在这里了

**Comment by MHuiG** [comment]
改成`5.0.0-alpha.3`试试看

**Comment by MHuiG** [comment]
清除一下浏览器缓存 
![image](https://user-images.githubusercontent.com/38281581/100530327-8b7ade80-322b-11eb-8a46-939276765345.png)

**Comment by lei2rock** [comment]
改成`5.0.0-alpha.3`后Safari和Edge均可加载评论框里，但是：

1. 依然无法正常加载表情包。
<img width="714" alt="image" src="https://user-images.githubusercontent.com/19180725/100537055-22fa2480-3260-11eb-994a-f9f08752d856.png">

2. 评论后无法自动加载新评论
<img width="690" alt="image" src="https://user-images.githubusercontent.com/19180725/100537176-2d68ee00-3261-11eb-8dd7-d69fbafd64ab.png">


3. 此外，还是无法读取原来Valine的评论数据，似乎是因为和Valine对于评论所在页面url的存储不一样。

**Comment by MHuiG** [comment]
控制台什么情况

**Comment by lei2rock** [comment]
提交后出现
<img width="520" alt="image" src="https://user-images.githubusercontent.com/19180725/100537296-3ad2a800-3262-11eb-88a5-adbda275277e.png">

对于Edge，刷新加载评论后控制台不报错；对于Safari，加载评论后
<img width="559" alt="image" src="https://user-images.githubusercontent.com/19180725/100537331-7e2d1680-3262-11eb-9dab-f6906fe93a02.png">

**Comment by MHuiG** [comment]
500错误是服务器端错误

**Comment by lei2rock** [comment]
另外，对于无法读取原来Valine的评论数据，似乎是因为和Valine对于评论所在页面url的存储不一样。对比一下：

对于独立页面
MiniValine：`/photos/index.html`
Valine：`/photos/`

对于文章：
MiniValine：`//posts/50/`
Valine：`/posts/50/`

对比看感觉Valine的更符合逻辑

**Comment by lei2rock** [comment]
> 500错误是服务器端错误

服务器端我再看看吧，感觉没出什么问题，也可以正常发送评论通知，可以后台读取管理各个评论（包括Valine历史评论）

**Comment by lizheming** [comment]
服务端错误可以把错误信息发一下诶特下我，我可以协助帮忙看一下

**Comment by lei2rock** [comment]
> 服务端错误可以把错误信息发一下诶特下我，我可以协助帮忙看一下

可以在哪里看到错误记录吗，我目前没出来哪里有问题，都是按照文档部署的，docker compose 部署，服务端链接 https://waline.dlzhang.com

```
version: '3'

services:
    wlaine:
        image: lizheming/waline
        container_name: waline
        restart: always
        ports:
            - '8360:8360'
        environment:
            LEAN_ID: 'xxx'
            LEAN_KEY: 'xxx'
            LEAN_MASTER_KEY: 'xxx'
            SITE_NAME: '醉里挑灯赏猫'
            SITE_URL: 'https://blog.dlzhang.com'
```
