### ISSUE TITLE
WebSocket 连接错误

### ISSUE THREAD

**Issue by Adkinsm2020** [MiniValine/MiniValine#409]
Please follow this Issue template to provide relevant information, such as source code repositories, blog links, and screenshots, which will help us investigate.
请按照此 Issue 模版提供相关信息，例如源码仓库、博客链接和屏幕截图，这将有助于我们进行调查。

## Issue Checklist 

- [x] I am using [the latest](https://github.com/MiniValine/MiniValine/releases/latest) version of MiniValine.
- [ ] I have reviewed the [MiniValine FAQs](https://minivaline.js.org/docs/en/#/FAQ), which does not help me.
- [x] I have searched for current [issues](https://github.com/MiniValine/MiniValine/issues), which does not help me.

***

## Expected behavior 

本应该正常出现的才对

## Actual behavior 
Firefox 提示 `Firefox 无法建立到 wss://talk.admin.blog.adkimsm.asia/ws 服务器的连接。`
Chromium_Edge提示 `WebSocket connection to 'wss://talk.admin.blog.adkimsm.asia/ws' failed:`

- Links to demo site with this issue: <https://blog.adkimsm.asia/>
- Links to repository or source code of the blog: N/A

## Steps to reproduce the behavior 

切换评论系统到MiniValine后即出现

### Node.js and NPM Information
Vercel 集成部署。
```

```

### Package dependencies Information

```
hexo g 无任何报错
```

### HTML Configuration

hexo-theme-yun的配置：
```
minivaline:
  enable: true
  # 更多选项 https://minivaline.js.org/docs/cn/#/Options 按照yml格式继续填写即可 （除了 [el] 选项）
  # emoticonUrl 等列表选项 可参考 https://github.com/MiniValine/hexo-next-minivaline
  # 下面是一个例子：
  serverURL: http://talk.admin.blog.adkimsm.asia/
```

## Other Information 
firefox·`93.0b9`·
edge`94.0.992.38 `
